version: '3'
services:
  devbox:
    build:
      context: ./
      dockerfile: Silverstripe.Dockerfile
    ports:
      - 80:80

    volumes:
      - ./app/:/var/www/html
        # this takes advantage of the feature in Docker that a new anonymous
        # volume (which is what we're creating here) will be initialized with the
        # existing content of the image at the same location
    restart: always
  devmysql:
    build:
      context: ./
      dockerfile: MySQL.Dockerfile
    ports:
      - "6060:3306"
    volumes:
      - ./data/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
