apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckhunt1
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: ducks
          image: steeloctopus/duckhunt:1.0
          ports:
            - containerPort: 80