apiVersion: apps/v1
kind: Deployment
metadata:
  name: ducks-deployment
spec:
  selector:
    matchLabels:
      app: ducks
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ducks
    spec:
      containers:
        - name: ducks
          image: steeloctopus/duckhunt:1.0
          ports:
            - containerPort: 80